### ISSUE TITLE
ペーストが実行されない？

### ISSUE THREAD

**Issue by Kendaman** [itagagaki/charu3-SE#51]
ソフトウェアの引継ぎ更新ありがとうございます
SEバージョンを早速使ってみたのですが、通常モードストックモードに関わらずクリップボードへの格納は行われますが
テキストウィンドウへのペースト処理が実行されないようです。色々設定を弄ってみましたが特に変化なく…
OSはWindows 10 Proです

**Comment by itagagaki** [comment]
ペースト対象ウィンドウは何でしょうか？
たとえばメモ帳にもペーストされないでしょうか？
「キーイベント設定」で「貼り付けに使うキー」は Ctrl + V になっているでしょうか？
「特定のウィンドウでの設定」には何か設定されていますでしょうか？
クリップボードへの格納は行われるということは、その後手動で Ctrl + V をタイプしたらペーストされるのでしょうか？

**Comment by Kendaman** [comment]
返信ありがとうございます。
ペースト対象はアプリケーション問わずテキスト系全てがダメみたいです
自宅のPC（Windows 10 Home）でも同様でした。貼り付けに使うキー・特定のウィンドウ設定も特に設定なしです。
クリップボードへの格納は問題なく行われており、Ctrl+Vで貼り付けできます。
旧バージョンでは項目のダブルクリック、ストックモードでのペースト上手く行きますが、SEバージョンは最新版ベータ版どれもダメみたいです。

気になったのでVisual Studio 2019でデバッグしつつ確認しましたが、どうもアクティブなWndへのデータの受け渡しが上手く行っていないような気がします。
と言ってもクリップボードへの格納処理はどこかわかりましたが、肝心のアクティブウィンドウへのペーストはどこで行っているかわからなかったので定かではありませんが…

**Comment by itagagaki** [comment]
Enterキーでも同じでしょうか？
貼り付けに使うキーをたとえば A にして、メモ帳でCharu3 SEのデータツリーからデータ項目をダブルクリック、または選択してEnterキーをタイプすると、メモ帳には a が入力されると思います。これもそうならないようでしたら、ご推測のとおりアクティブなウィンドウにキーイベントが行っていない可能性がありますね。

ペーストを行っているのは Charu3.cpp の `CCharu3App::pasteData()` です。
Charu3 SEでは `key.m_nMessage` は常に 0 になっているはずなので 1348 行を通ると思います。
Visual Studio を使って、そこでデバッグ確認することができると思いますし、または、
`%AppData%\Charu3\settings.json` で "debug": true にして実行すれば 1362 行のデバッグプリントも通るようになるので、それを Visual Studio の出力ウィンドウかファイル `%AppData%\Charu3\debug.log` で確認することもできると思います。
ご協力いただけるでしょうか？
よろしくお願いいたします。

**Comment by itagagaki** [comment]
ありがとうございます。
どうやら `keyEvent.default.method` の初期化のコードにミスがありそうです。

`%AppData%\Charu3\settings.json` に下記のブロックがあると思います。
おそらく `"method": 0` になっていない（1313288 になっているか、もしくは method 自体存在していない）と思われますので、`”method": 0` に修正してみていただけますでしょうか。

```
	"keyEvent.default": {
		"copy.delay": 50,
		"copy.keyCode": 2,
		"copy.keyModifier": 67,
		"copy.message": {
			"id": 769,
			"param1": 0,
			"param2": 0
		},
		"method": 0,
		"paste.delay": 50,
		"paste.keyCode": 2,
		"paste.keyModifier": 86,
		"paste.message": {
			"id": 770,
			"param1": 0,
			"param2": 0
		}
	},
```

お手数をおかけしますがよろしくお願いいたします。

**Comment by Kendaman** [comment]
ありがとうございます、貼り付け処理まで辿り着いていたのにmethodを完全に見逃していました…！
ご指摘の通り、methodを0に変更することでペーストが正常に動作するようになりました！
処理的には問題がなかったようですので、後はmethodの初期値が正しく設定されれば問題ないかと存じます。
大変迅速な調査、解決方法の発見、ありがとうございました！

**Comment by itagagaki** [comment]
3.8.2 をリリースしました。
もしご協力いただけるなら、`%AppData%\Charu3` を削除または退避してからの初回起動で正常な初期設定がされることを確認していただけると大変助かります。

**Comment by itagagaki** [comment]
すみません。修正をさらに加えて 3.8.3 をリリースしました。テスト不足で申し訳ありません。
検証していただけると助かります。
よろしくお願いいたします。

**Comment by Kendaman** [comment]
修正ありがとうございます！
Appdataの設定フォルダを削除してから起動し操作してみましたが、バッチリ機能しました！
methodも"method": 0,と記入されますので問題なさそうです。修正お疲れ様でした！

**Comment by itagagaki** [comment]
検証ありがとうございます。おかげさまで安心してリリースできます。
