### ISSUE TITLE
Portable mode

### ISSUE THREAD

**Issue by itagagaki** [itagagaki/charu3-SE#53]
### Discussed in https://github.com/itagagaki/charu3-SE/discussions/43

<div type='discussions-op-text'>

<sup>Originally posted by **itagagaki** June  5, 2023</sup>
I changed the location of the preferences file (and so on) to %UserProfile% on Apr 21.
However, I will consider allowing users to choose portable mode.
</div>

**Comment by itagagaki** [comment]
It would be helpful if you could test the attached binary.

[Charu3_branch53.zip](https://github.com/itagagaki/charu3-SE/files/12498095/Charu3_branch53.zip)

**Comment by Lichtenshtein** [comment]
> It would be helpful if you could test the attached binary.

Portable mode works.

**Comment by itagagaki** [comment]
Thanks for testing. This feature has been merged into the master branch for the next 3.9.0 release.
