### ISSUE TITLE
When the Windows display language is Russian, Alt + Q cannot be registered as a hotkey

### ISSUE THREAD

**Issue by itagagaki** [itagagaki/charu3-SE#56]
There is a detailed report in #52 
I will look into this issue.

**Comment by itagagaki** [comment]
I got the cause. Failure to register Alt + Q as a hotkey because there is no key for Q in the Russian key layout. I don't understand, how do people who use Russian keyboard type the alphabet?

**Comment by Lichtenshtein** [comment]
> Failure to register Alt + Q as a hotkey

Not only Alt + Q... Any keyboard shortcut set for fragments or folders in the data tree does not work in when launching Charu with (RUS) layout. I found a quick explanation for you, but it can hardly be particularly useful. See "The why" section:

https://github.com/microsoft/vscode/issues/141761#issue-1117836208

**Comment by itagagaki** [comment]
Thank you for the info.
I have added a countermeasure. I'm a little unsure if it's the right fix, but I'll adopt it if it solves the problem for now.
I am concerned that there is no degradation, so could you please test it for a while?
[Charu3_20230921.zip](https://github.com/itagagaki/charu3-SE/files/12679343/Charu3_20230921.zip)

**Comment by Lichtenshtein** [comment]
If i use my own settings file, inserting text from the data tree and any operations with selected text do not work. You need to go to Charu settings and reconfigure the hotkeys for copying and pasting, even if they are the same. Then everything works.

If make Charu recreate the settings file as if it was the first launch, then everything described above works as it should.

As for the non-functioning hotkeys when launching in regional language layout, it seems that now they work.

HotkeyScreener:
`Alt + Q Charu3.exe (PID: 12492)`

> I am concerned that there is no degradation, so could you please test it for a while?

I will test a little more if you want.

**Comment by itagagaki** [comment]
I have not been able to reproduce the problem of having to redo the key settings, so I am not sure what caused it on your end. I will see what happens after the next release.
