### ISSUE TITLE
Extraneous symbols in the name of items after paste and copy operations in the data tree.

### ISSUE THREAD

**Issue by Lichtenshtein** [itagagaki/charu3-SE#57]
I just noticed that if you select item in the data tree, click "Copy Item" in the context menu, and then "Paste Copied Item", then extraneous characters "????" are added to the name of pasted item.

![test123](https://github.com/itagagaki/charu3-SE/assets/13855295/bd9fee8c-c01d-4827-b315-0a18bc1379a8)

**Comment by itagagaki** [comment]
It may be a localization leak. I will fix it.

**Comment by Lichtenshtein** [comment]
This is fixed, thank you. Closing.
