### ISSUE TITLE
With high DPI settings in Windows, the text in Charu's settings does not fit into the forms

### ISSUE THREAD

**Issue by Lichtenshtein** [itagagaki/charu3-SE#58]
Interface scaling in Windows is set to 125%. The text in the settings "climbs" a bit behind the elements.

it's not critical, but noticeable.

![234](https://github.com/itagagaki/charu3-SE/assets/13855295/7c33fc4d-c40a-4722-9679-58fece535b7a)

**Comment by itagagaki** [comment]
It does not reproduce in my environment. What could be the difference?

**Comment by Lichtenshtein** [comment]
I have Windows 10 LTSB.

I rechecked, for some reason it is reproduced only at 125% scale. The text and interface in the Charu settings is scaled correctly at 150% and 200%.

I change interface scaling like this (translated from russian):

Classic Windows Control Panel → All control panel elements → Screen → Resizing elements → Find on the page "set a custom zoom level" (customscaledialog) → Custom resizing options → Scale from the normal size: 125%, Font size 9.

I'm not doing this through PC Settings because in this version of Windows changing interface zooming in there led to blurring of everything.

**Comment by itagagaki** [comment]
This may be a past Windows issue that has been fixed in the latest version of the current Windows 10 SAC. I am not sure if that fix is reflected in the LTSB update. Note that in the SAC, the Display item has now been moved to the Settings app instead of the Control Panel.

But I'll try to expand the space to the right of the each text a bit if possible.

**Comment by Lichtenshtein** [comment]
I read that all similar issues have been resolved in subsequent releases, and that there is no longer a familiar control panel too. LTSB is very stable, fast, and i am used to it, sorry. I was planning to upgrade when i buy new hardware (currently it is from ~2011). I don't have the opportunity to do it yet.

Thank you for still fixing it.

Not something Charu has control over, closing the issue.
